// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AdminTournamentController from "./admin_tournament_controller"
application.register("admin-tournament", AdminTournamentController)

import BracketFormController from "./bracket_form_controller"
application.register("bracket-form", BracketFormController)

import BracketPickerController from "./bracket_picker_controller"
application.register("bracket-picker", BracketPickerController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import FilterBracketsController from "./filter_brackets_controller"
application.register("filter-brackets", FilterBracketsController)

import InlineEditController from "./inline_edit_controller"
application.register("inline-edit", InlineEditController)

import LineCounterController from "./line_counter_controller"
application.register("line-counter", LineCounterController)

import PullToRefreshController from "./pull_to_refresh_controller"
application.register("pull-to-refresh", PullToRefreshController)

import AnalysisChartController from "./analysis_chart_controller"
application.register("analysis-chart", AnalysisChartController)
